site_name: Lily58ドキュメントページ
use_directory_urls: false
theme:
  name: material
  language: ja
plugins:
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       width: 100%
       height: auto
       zoomable: true
       draggable: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
    - Lily58の概要: index.md
    - Lily58 Pro:
      - Lily58 Pro 概要: Lily58_Pro.md
      - Lily58 Pro 必要な部品: Lily58_Pro_Parts.md
      - Lily58 Pro ビルドガイド: Lily58_Pro_BG.md
      - Lily58 Pro ヘルプページ: Lily58_Pro_Help.md
    - Lily58 Lite Rev2:
      - Lily58 Lite Rev2 概要: Lily58_Lite_Rev2.md
      - Lily58 Lite Rev2 必要な部品: Lily58_Lite_Rev2_Parts.md
      - Lily58 Lite Rev2 ビルドガイド: Lily58_Lite_Rev2_BG.md
    - お問い合わせ: contact.md
    - 古い情報:
      - Lily58 ビルドガイド: Lily58_BG.md
      - Lily58 Lite 必要な部品: Lily58_Lite_Parts.md
      - Lily58 Lite ビルドガイド: Lily58_Lite_BG.md